### PR TITLE
Fixed building on Windows for Visual Studio and MinGW

### PR DESCRIPTION
**Pull request by MOZGIII**
Additional fix for two popular compilers (see #2).

### CODE REVIEW

**Comment by falceeffect** [comment]
Can I straight-merge it, or it requires additional testing? :D

**Comment by MOZGIII** [comment]
"Try me!" :P

**Comment by falceeffect** [comment]
Seriously, I usually use Linux, hate unnecessary rebooting. >.<

**Comment by MOZGIII** [comment]
Check it on Linux & Mac, Windows is sort of covered :/

**Comment by falceeffect** [comment]
Linux is fine, Mac is probably too, as this one doesn't affect it at all.

**Comment by bakwc** [comment]
i can try to test and fix it on windows

**Comment by MOZGIII** [comment]
@falceeffect yep.
@bakwc try please, my environment might now cover all edges.

**Comment by bakwc** [comment]
Tested on windows gcc-mingw, everything seems fine.

**Comment by MOZGIII** [comment]
Thanks, good job guys!

**Pull request merged**
